[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[dev]
  port = 3000
  functions = "netlify/functions"
  command = "npm run dev"
  targetPort = 3001
  functionsPort = 9999
  timeout = 120

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
